name: github action CI

on: workflow_dispatch

env:
  IMAGE_NAME: cloud-sample

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.REPO_TOKEN }}
        
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Setup Kustomize
      uses: imranismail/setup-kustomize@v1

    - name: 'Gen Version'
      id: gen-version
      run: |
        echo "::set-output name=VERSION::`date +%Y%m%d%H%M`"
        
    - name: 'ACR login'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.BASEACR_LOGIN_SERVER  }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: 'Build & Tag Image'
      run: |
            docker build -t ${{ secrets.BASEACR_LOGIN_SERVER  }}/${{ env.IMAGE_NAME }}:${{ steps.gen-version.outputs.VERSION }} -f Dockerfile-maven .
            docker tag ${{ secrets.BASEACR_LOGIN_SERVER  }}/${{ env.IMAGE_NAME }}:${{ steps.gen-version.outputs.VERSION }} ${{ secrets.STAPACR_LOGIN_SERVER  }}/${{ env.IMAGE_NAME }}:${{ steps.gen-version.outputs.VERSION }}
    
    - name: 'Push image'
      uses: azure/docker-login@v1
      with:
        login-server: ${{ secrets.STAPACR_LOGIN_SERVER  }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
          docker push ${{ secrets.STAPACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.gen-version.outputs.VERSION }}
    
    - name: Update Kubernetes resources
      run: |
          echo "`ls`"
          cd manifests/overlays/prod
          kustomize edit set image ${{ secrets.STAPACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ steps.gen-version.outputs.VERSION }}
          cat kustomization.yaml
    
    - name: Commit files
      run: |
          cd manifests
          echo "`ls`"
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git commit -am "Update image tag"
          git push -u origin main
